### ISSUE TITLE
Use CMake instead of Makefile

### ISSUE THREAD

**Issue by natis1** [natis1/openlife#1]
See title, makes compiling a heck of a lot more robust and allows for configuring compiling commands

**Comment by LSaldyt** [comment]
This definitely seems like a good idea, so if you have experience with CMake, go ahead (not that you need my okay). 

Side note - I haven't used CMake before, but I'm sure I can figure it out.

**Comment by natis1** [comment]
I'm going to add a script so just having cmake and the graphics library installed will be enough to build an executable. For normal users it's identical to a makefile but with two advantages

You can customize your install if you want. It will be easier to do static builds, different optimization levels, debugging flags, etc.

It's easier to fix stuff compared to a normal makefile

It's all scripting like a makefile though.

**Comment by natis1** [comment]
Fixed with PR 2
