### ISSUE TITLE
Cells tend towards the right

### ISSUE THREAD

**Issue by natis1** [natis1/openlife#22]
Then they hit the right wall. If you add damage to hitting the walls (so they die on impact) they will all march to their deaths leaving a bunch of space on the left open, but unused.

**Comment by LSaldyt** [comment]
Looks like this is unrelated to the piece of code that was removed in `updateInteractions`, which ensures that cell interactions only happen once per turn:

Consider a list of cells `[a, b, c]`
An interaction `a->b` is the same as `b->a`
So, the only interactions that need to happen are:
`a->b a->c b->c`
With the code that you had modified, the interactions happening were:
`a->b a->c b->a b->c c->a b->b`

**Comment by LSaldyt** [comment]
This bug was introduced during the merge of `nogui` (between 7b20a92c47f2c723c3b74c28a819280170f5a1c7 and the successful merge: 3487f288d344db852b5c70fff45a2e4f3fad8ed8). Run the `post-merge-success` branch to see the bug

With a small graphical fix to `nogui`, it is unclear if the bug originated here. I recommend checking out `nogui` and running the graphical executable to check if this is where it started. Alternatively, the bug may have come during the several merge commits. I will look into this.

Note: master is level with population-dynamics, so it does not display the bug either

**Comment by LSaldyt** [comment]
Testing of pre-merge commit (7b20a92) shows that even if turn rate is increased, cells do not move to the right. So, we have further reason to believe that this bug was introduced during the merge of `nogui`

**Comment by natis1** [comment]
Angle detection code is different between develop and nogui, so it might be worth using the nogui code instead.

**Comment by LSaldyt** [comment]
What do you mean by angle detection code? (I'm assuming the functions calculateIdealAngle and calculateNextAngle, which are now combined in intelligentRotate) Also, develop's angle calculation code is unit tested. I'm not sure if nogui's is.

**Comment by natis1** [comment]
I meant angle calculation code. No idea if nogui's code works or not. How exactly were the unit tests done?

**Comment by LSaldyt** [comment]
They're pretty simple, but definitely test functionality. I've added some changes so that all the angles are normalized:
``` cpp
        Cell a, b;
        REQUIRE(almostEqual(distance(a, b), 0.));
        a.move(1, 0); // Move right 1
        REQUIRE(almostEqual(distance(a, b), 1.) );
        REQUIRE(almostEqual(angle(a.getPosition(), b.getPosition()), 0.) );
        a.move(0, 1); // Move up 1
        REQUIRE(almostEqual(angle(a.getPosition(), b.getPosition()), 45.) );
        a.move(-2, -2.); // Move to third quadrant 
        REQUIRE(almostEqual(angle(a.getPosition(), b.getPosition()), 225.) );

```

**Comment by LSaldyt** [comment]
Also, it looks like `nogui`'s angle calculation is shifted 90 degrees when it shouldn't be. Otherwise, the two functions are the same (`atan2(y_delta, x_delta)`). The version on develop is definitely correct.

**Comment by natis1** [comment]
Okay then it would be worth it using the code from develop to fix it, or else rewriting it but taking inspiration from develop.

**Comment by LSaldyt** [comment]
It looks like there are some cases where cells tend to the left, instead
(Either way, they polarize in one direction, which is unideal)
This change in direction seems to be related to the latest two commits on develop

**Comment by LSaldyt** [comment]
Looks like bug still isn't related to angle calc code. See latest commits on develop.

**Comment by LSaldyt** [comment]
I've found a possible source of this issue: a parameter tweak to neighbor/search radii. You can replicate this by making the radii significantly smaller in `params.txt`. The debugging features I've added should demonstrate why this might be causing the bug. Cheers.

Specifically, if you want to replicate the bug, change search radius from 500 to 100. All of the cells should move to the left.

**Comment by LSaldyt** [comment]
Removing cell bouncing fixes this entirely, and I think the new borderless feature is much classier than bouncing anyways.
