### ISSUE TITLE
Cells currently have no pathfinding

### ISSUE THREAD

**Issue by LSaldyt** [natis1/openlife#4]
It could be nice to make them move either toward or away from other cells, depending on their situation (Under vs Over populated). Some (deterministic) imperfection in movement would be a nice touch, too.

**Comment by natis1** [comment]
I will work on this tomorrow morning. One thought might be having cells with their colors representing their behaviours (like DNA or something) and determining how they turn. If colors are implemented in a deterministic way this could work.

**Comment by LSaldyt** [comment]
Sounds good. Right now, colors are averaged between the two parents, which is deterministic, but if we did this, we might create a different formula for crossing over two colors.

**Comment by natis1** [comment]
Yeah, I will mess with the formulas until I get something that works really well. Alternatively I could work on an actual AI but I feel like keeping this system fairly simple would be better so in either situation it probably will not be too complex.

**Comment by natis1** [comment]
^ Ignore that, I'm still trying to figure out how this stuff works.

But yeah cells currently rotate based on color. One thing cool about the original game of life is that each cell only cares about it's neighbor cells and nobody else. I am going to continue working on this further, maybe, for example, less promiscuous cells try to avoid large groups leading to longer life but they reproduce slower.

**Comment by natis1** [comment]
I've been looking at http://www.red3d.com/cwr/boids/ the other day and I realized making a deterministic movement system based on simple rules is relatively easy with good cell telemetry, so I am going to implement some of that and see what works.

http://hughsk.io/boids/ Here's a browser implementation

**Comment by LSaldyt** [comment]
Interesting. You might consider making a `pathfinding-feature` branch if you plan on doing some extensive work with pathfinding or cell behavior in general

**Comment by natis1** [comment]
Yeah, that's what I have but I haven't pushed it yet, so it's not on the Github. I reckon I will have some working pathfinding algorithms in a few days.
