### ISSUE TITLE
Cells are restricted to window size

### ISSUE THREAD

**Issue by LSaldyt** [natis1/openlife#8]
Currently, cells are told they are out of bounds when their position exceeds the window's borders. This is a simple change (supplying a different `borders` vector to the cells for bounds checking).
However, it would be nice to:
- zoom in and out
- pan the camera
- have a visual indication of where the borders are
- eventually remove borders entirely, and make the simulation (seemingly) infinite

**Comment by LSaldyt** [comment]
Current progress:
![Less restrictive bordering](http://i.imgur.com/keGF6kK.png)

Features that have been added:
- border is separate from window size
- scrolling the mouse zooms in/out
- WASD moves the viewport

Improvements that can still be made:
- Smooth movement with WASD
- Addition of arrow keys for movement
- Cleaner key recognition

**Comment by natis1** [comment]
Milestones don't work quite the way you think they do :P (trust me I had trouble with that yesterday). Anyway I am going to tomorrow work on further decoupling as much as possible the cells from the graphics data.

**Comment by LSaldyt** [comment]
I tried doing partially implemented, but I realize that doesn't work. Instead, I created the Beta milestone (two weeks from now - why not?). Hopefully this is correct :P
Decoupling sounds good - if there is anything you want me to do for that, or any code you want explained, just ask.

**Comment by natis1** [comment]
Oh no, it's all good, it took me a bit to understand the code at first but once I got the hang of it everything seems just fine.
